server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-micro-service
          uri: lb://USER-MICRO-SERVICE
          predicates:
            - Path=/user-micro-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-micro-service/(?<segment>.*), /$\{segment}

        - id: user-micro-service
          uri: lb://USER-MICRO-SERVICE
          predicates:
            - Path=/user-micro-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-micro-service/(?<segment>.*), /$\{segment}

        - id: user-micro-service
          uri: lb://USER-MICRO-SERVICE
          predicates:
            - Path=/user-micro-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-micro-service/(?<segment>.*), /$\{segment}

#        - id: user-micro-service
#          uri: lb://USER-MICRO-SERVICE
#          predicates:
#            - Path=/user-micro-service/**
        - id: catalog-micro-service
          uri: lb://CATALOG-MICRO-SERVICE
          predicates:
            - Path=/catalog-micro-service/**

        - id: order-micro-service
          uri: lb://ORDER-MICRO-SERVICE
          predicates:
            - Path=/order-micro-service/**

        - id: first-service
          uri: lb://MY-FIRST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
#            - AddRequestHeader=first-request, first-request-header2
#            - AddResponseHeader=first-response, first-response-header2
            - CustomFilter
        - id: second-service
          uri: lb://MY-SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
#            - AddRequestHeader=second-request, second-request-header2
#            - AddResponseHeader=second-response, second-response-header2
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, there.
                preLogger: true
                postLogger: true
